version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Han1804!
      MYSQL_DATABASE: project_vote_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "
      until mysqladmin ping -h db -uroot -pHan1804! --silent; do
        echo 'Waiting for MySQL...'; sleep 2;
      done;
      echo ' MySQL is up. Starting Django...';
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    
volumes:
  db_data:



